import localFont from "next/font/local";
import "./globals.css";
import { Roboto_Mono, Lobster, Lato, Fira_Sans } from "next/font/google";

const roboto = Roboto_Mono({
  weight: [ "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
const lato = Lato({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
const as = Lobster({
  family: ["Lobster Two", "sans-serif"],
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});
const fira = Fira_Sans({
  family: ["Fira Sans", "sans-serif"],
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className={roboto.className}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
